services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: exampledb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
