services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9050:9000"
      - "9051:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
